name: build and push docker images

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_run:
    workflows:
      - Create Tag
    types:
      - completed

jobs:
  build:
    name: Build and Push Multi-arch Docker Images
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository at tag
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TAG }}

      - name: Determine tag
        id: determine_tag
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
            # Извлекаем тег из GITHUB_REF для события push
            TAG=${GITHUB_REF#refs/tags/}
            echo "Detected push event with tag: $TAG"
          elif [[ "${GITHUB_EVENT_NAME}" == "workflow_run" ]]; then
            # Для workflow_run выполняем fetch тегов и выбираем последний SemVer тег
            git fetch --tags
            TAG=$(git tag -l | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n1)
            if [ -z "$TAG" ]; then
              echo "❌ Тег не найден. Завершаем сборку."
              exit 1
            fi
            echo "Detected workflow_run event with tag: $TAG"
          else
            echo "❌ Unsupported event: ${GITHUB_EVENT_NAME}"
            exit 1
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "::set-output name=tag::$TAG"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deployments/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ebook-convert-wrapper:${{ env.TAG }}
            ghcr.io/${{ github.repository_owner }}/ebook-convert-wrapper:latest