name: build and push docker images

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_run:
    workflows:
      - Create a new tag
    types:
      - completed

jobs:
  build:
    name: Build and Push Multi-arch Docker Images
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: deployments/docker
          file: deployments/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ebook-convert-wrapper:latest
            ghcr.io/${{ github.repository_owner }}/ebook-convert-wrapper:${{ github.ref_name }}