name: build and push docker images

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_run:
    workflows:
      - Create Tag
    types:
      - completed


jobs:
  build:
    name: Build and Push Multi-arch Docker Images
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Determine tag
        id: determine_tag
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            # Для события push тег извлекается из github.ref
            TAG=${GITHUB_REF#refs/tags/}
            echo "Detected push event with tag: $TAG"
          elif [[ "${{ github.event_name }}" == "workflow_run" ]]; then
            # Для workflow_run тег берётся из head_branch
            TAG=${{ github.event.workflow_run.head_branch }}
            echo "Detected workflow_run with tag: $TAG"
          else
            echo "Unsupported event: ${{ github.event_name }}"
            exit 1
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "::set-output name=tag::$TAG"

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TAG }}


      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deployments/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ebook-convert-wrapper:${{ env.TAG }}
            ghcr.io/${{ github.repository_owner }}/ebook-convert-wrapper:latest