name: build and push docker images

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_run:
    workflows:
      - Create Tag
    types:
      - completed


jobs:
  build:
    name: Build and Push Multi-arch Docker Images
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deployments/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ebook-convert-wrapper:latest
            ghcr.io/${{ github.repository_owner }}/ebook-convert-wrapper:${{ github.ref_name }}